export var City: string[] = [
    'Acre'
    , 'Afula'
    , 'Arad'
    , 'Ariel'
    , 'Ashdod'
    , 'Ashkelon'
    , 'Bat Yam'
    , 'Beersheba'
    , 'Beit Shean'
    , 'Beit Shemesh'
    , 'Beitar Illit'
    , 'Bnei Brak'
    , 'Dimona'
    , 'Eilat'
    , 'Elad'
    , 'Givat Shmuel'
    , 'Givatayim'
    , 'Hadera'
    , 'Haifa'
    , 'Herzliya'
    , 'Hod HaSharon'
    , 'Holon'
    , 'Jaffa'
    , 'Jerusalem'
    , 'Karmiel'
    , 'Kiryat Arba'
    , 'Kiryat Ata'
    , 'Kiryat Bialik'
    , 'Kiryat Gat'
    , 'Kiryat Malakhi'
    , 'Kiryat Motzkin'
    , 'Kiryat Ono'
    , 'Kiryat Shmona'
    , 'Kiryat Tivon'
    , 'Kiryat Yam'
    , 'Kfar Saba'
    , 'Lod'
    , 'Maale Adumim'
    , 'Maalot-Tarshiha'
    , 'Metula'
    , 'Migdal HaEmek'
    , 'Modiin-Maccabim-Reut'
    , 'Modiin Illit'
    , 'Nahariya'
    , 'Nazareth Illit'
    , 'Nesher'
    , 'Ness Ziona'
    , 'Netanya'
    , 'Netivot'
    , 'Ofakim'
    , 'Or Akiva'
    , 'Or Yehuda'
    , 'Petah Tikva'
    , 'Raanana'
    , 'Ramat Gan'
    , 'Ramat HaSharon'
    , 'Ramla'
    , 'Rehovot'
    , 'Rishon LeZion'
    , 'Rosh HaAyin'
    , 'Rosh Pina'
    , 'Safed'
    , 'Sderot'
    , 'Tel Aviv'
    , 'Tiberias'
    , 'Tirat Carmel'
    , 'Yavne'
    , 'Yehud-Monosson'
    , 'Yokneam'
    , 'Zikhron Yaakov'
]

